server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bootdo
    username: abel
    password: abel123
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    root: info
    org.mybatis: info
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  